development:
  adapter: postgresql
  database: knowledgr_prelaunchr_development
  host: localhost
  username: admin
  password: password
test:
  adapter: postgresql
  database: knowledgr_prelaunchr_test
  host: localhost
